FROM python:3.10
 
# ENV PYTHONDONTWRITEBYTECODE=1
# ENV https_proxy="http://172.16.20.207:3128"
# ENV http_proxy="http://172.16.20.207:3128"
# ADD app app
COPY ./src/requirements.txt /src/requirements.txt
WORKDIR /src